name: 'Terraform with Akeyless Secrets'

on:
  workflow_dispatch:

permissions:  
  id-token: write       # required by akeyless
  contents: read        # required by akeyless and terraform
  pull-requests: write  # required by terraform

env:
  TF_CLOUD_ORGANIZATION: "grib-org1"           # name of the Terraform organization
  TF_WORKSPACE: "api"                          # name of the Terraform workspace
  CONFIG_DIRECTORY: "./"                       # directory in the rpo that has the config files
  # TF_API_TOKEN: "${{secrets.TF_API_TOKEN}}"  # do NOT set this anymore, Akeyless will do it for you

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # THIS GETS YOUR TEAM-TOKEN FROM AKEYLESS!
    # - The static secret is fetched and automatically exported into TF_API_TOKEN
    # - The 'access-id' is the Auth Method ID from Akeyless (see docs or talk to George Ribarski)
    - name: Fetch static secret from AKeyless
      id: akeyless
      uses: LanceMcCarthy/akeyless-action@v4
      with:
        access-id: 'p-149l6gayzx05'
        static-secrets: '{"/DevTools/terraform-team-token-owners":"TF_API_TOKEN"}'  

    - name: Upload Configuration
      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
      id: plan-upload
      with:
        workspace: ${{env.TF_WORKSPACE}}
        directory: ${{env.CONFIG_DIRECTORY}}
        speculative: true

    - name: Create Plan Run
      uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
      id: plan-run
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
        plan_only: true

    - name: Get Plan Output
      uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
      id: plan-output
      with:
        plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}