name: Rich and Chet Repro
on:
  workflow_dispatch:
  push:
    branches:
      - 'rick-chet-tester'

jobs:
  build_api:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-22.04
    steps:
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: docker build
      id: build-images
      working-directory: src/SecretsMocker/SecretsMocker
      run: |
        # need to make this username all lowercase, so copying it into a separate var
        OWNER=${{github.repository_owner}}
        # build and push to GH user's ghcr.io reigstry
        docker buildx build --push --platform 'linux/arm64,linux/amd64' -t "ghcr.io/${OWNER,,}/secretsmocker:latest" -f Dockerfile .
        